jsp/urls.py
from django.urls import path
from jsp.views import *

app_name='cricket'
urlpatterns=[

path('yuvi/',yuvi,name='yuvi'),



]

psp/urls.py
from django.urls import path
from psp.views import *

app_name='ipl'
urlpatterns=[

path('gill/',gill,name='gill'),



]

specfic/urls.py
from django.contrib import admin
from django.urls import path,include
import jsp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('jsp/',include('jsp.urls')),
    path('psp/',include('psp.urls')),
    
]

jsp/models.py
from django.db import models

# Create your models here.

psp/models.py
from django.db import models

# Create your models here.

runserv/models.py
from django.db import models

# Create your models here.

runserver/models.py
from django.db import models

# Create your models here.

jsp/views.py
from django.shortcuts import render

# Create your views here.
def yuvi(request):
    return render(request,'yuvi.html')

psp/views.py
from django.shortcuts import render

# Create your views here.
def gill(request):
    return render(request,'gill.html')

runserv/views.py
from django.shortcuts import render

# Create your views here.

runserver/views.py
from django.shortcuts import render

# Create your views here.

templates/gill.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>**welcome**</h1>
        <h1> this page belongs to gill</h1>
        <h1>**record**</h1>
        <h1>**DONE DOUBLE CENTURY AND DONE CENTURYS</h1>

        <a href="{% url 'cricket:yuvi' %}">go to yuvi page</a>
    </center>
</body>
</html>

templates/yuvi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>**welcome**</h1>
        <h1> this page belongs to yuvi</h1>
        <h1>**record**</h1>
        <h1>**--6 balls --6 sixes**</h1>

        <a href="{% url 'ipl:gill' %}">go to gill page</a>
    </center>
</body>
</html>